kind: pipeline
type: docker
name: ci-pipeline

steps:
	-name: Run pytest
	image: python:3.9
	commands:
	- pip install --upgrade pip
	- pip install -r requirment/requirments.txt
	- pip install -r requirment/requirments_dev.txt
	- python -m pytest -v ./tests